open issue if no pipenv files are found
thoth-station/kebechet pull request #998
Opened 2022-02-11 15:31 UTC by KPostOffice

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/support/issues/150

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Open an issue for missing pipenv files if requirements manager is installed

2022-02-11 15:31 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **kpostoffice** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fkebechet).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/kebechet/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kpostoffice"]} -->

2022-02-14 12:48 UTC, codificat requested changes
Thanks for the fix!

I believe the message should be expanded a little bit more though

2022-02-14 12:48 UTC, codificat commented on kebechet/managers/pipfile_requirements/pipfile_requirements.py
> +        Either remove this manager from .thoth.yaml or use pipenv for requirements management.
I feel that the message could be expanded a bit more, to help (newer) users to better understand the problem and its resolution.

Maybe something along these lines:

```suggestion
        body = f"""Kebechet pipfile_requirements manager is installed but no `{file_name}` was found in this repository.
        
        `{file_name}` is required by the pipfile_requirements manager in its current configuration (as specified in `.thoth.yaml`).

        Either remove this manager from `.thoth.yaml`, adjust its configuration, or update the repository to meet the requirements.
        
        Reference: see the documentation for [pipfile_requirements](https://thoth-station.ninja/docs/developers/kebechet/managers/pipfile_requirements.html).
```

but feel free to improve

2022-02-22 19:43 UTC, sesheta commented
@KPostOffice: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 921e25214ba541e7df54fb80f488731ae0bfaf01 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_kebechet/998/pre-commit/1496208205053693952) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=kebechet&pr=998). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AKPostOffice). Please help us and [open an issue](https://github.com/thoth-station/kebechet/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-04 08:41 UTC, goern commented
whats missing to get this merged?

2022-03-04 20:32 UTC, KPostOffice commented
/approve

2022-03-04 20:32 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/kebechet/pull/998#issuecomment-1059509723" title="Approved">KPostOffice</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fkebechet).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/kebechet/blob/master/OWNERS)~~ [KPostOffice]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-04 20:42 UTC, merged